
- hosts: spine
  user: root
  roles:
    - common
    - ospfunnum
  vars_files:
    - roles/ospfunnum/vars/main.yml
  handlers:
    - include: handlers/main.yml

- hosts: leaf
  user: root
  roles:
    - common
    - ospfunnum
  vars_files:
    - roles/ospfunnum/vars/main.yml
  handlers:
    - include : handlers/main.yml
